include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disabled rules
    curly_braces_in_flow_control_structures: false
    use_key_in_widget_constructors: false # until SQ uses keys
    avoid_web_libraries_in_flutter: true # see mini_apps/js.dart

    # Error rules
    avoid_dynamic_calls: true
    discarded_futures: true

    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    comment_references: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_relative_imports: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unsafe_html: true

    # Style rules
    always_put_required_named_parameters_first: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    directives_ordering: true
    lines_longer_than_80_chars: true
    omit_local_variable_types: true
    parameter_assignments: true
    prefer_asserts_with_message: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_null_aware_method_calls: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    use_if_null_to_convert_nulls_to_bools: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true
    prefer_single_quotes: true
    prefer_expression_function_bodies: true
    no_default_cases: true
    only_throw_errors: true
    sort_constructors_first: true

    unnecessary_library_directive: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_double_and_int_checks: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_unused_constructor_parameters: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    dangling_library_doc_comments: true
    deprecated_consistency: true
    do_not_use_environment: true
    enable_null_safety: true
    eol_at_end_of_file: true
    implicit_call_tearoffs: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_annotations: true
    missing_whitespace_between_adjacent_strings: true
    noop_primitive_operations: true
    no_runtimeType_toString: true
    one_member_abstracts: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_foreach: true
    prefer_mixin: true
    sized_box_shrink_expand: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_raw_strings: true
    unreachable_from_main: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_string_in_part_of_directives: true
    use_test_throws_matchers: true

    # Pub rules
    secure_pubspec_urls: true
    sort_pub_dependencies: true

    # to enable:
    # avoid_classes_with_only_static_members # for SQApp and SQAuth
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# https://dart-lang.github.io/linter/lints/index.html
