
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    curly_braces_in_flow_control_structures: false
    unused_local_variable: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
    
    use_build_context_synchronously: true
    discarded_futures: true

    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    comment_references: true
    diagnostic_describe_all_properties: false
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_relative_imports: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unsafe_html: true

    # pubspec
    secure_pubspec_urls: true
    sort_pub_dependencies: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# https://dart-lang.github.io/linter/lints/index.html
